<a href="https://colab.research.google.com/github/jaewon-huh/DA_DS_dreamtree/blob/main/pandas_%EB%B3%B4%EC%B6%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 판다스 복습

In [1]:
import numpy as np
import pandas as pd 

df1 = pd.DataFrame(np.arange(12).reshape(3,4), columns =list('abcd'))
df2 = pd.DataFrame(np.arange(20).reshape(4,5), columns =list('abcde'))

In [2]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [3]:
df2

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [4]:
# 겹치지 않는 부분 : nan
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [5]:
# 존재하지 않는 부분의 값은 0으로 지정 
df1.add(df2, fill_value= 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

e열과 3행은 Nan 이 아닌 df2의 값으로 출력된다. 
(fill_value = 0 으로 df1의 존재하지 않는 값을 0으로 채움)

* DF와 Series의 연산 

In [6]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
arr[0]

array([0, 1, 2, 3])

In [8]:
# df - series 
arr- arr[0]
# 각 로우에 대해 실행 (브로드 캐스팅)

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [9]:
frame = pd.DataFrame(np.arange(12).reshape((4,3)), 
                     columns = list('bde'),
                     index = ['A', 'B', 'C', 'D'])
series = frame.iloc[0]  # 0행

In [10]:
frame

b   d   e
A  0   1   2
B  3   4   5
C  6   7   8
D  9  10  11

In [11]:
series

b    0
d    1
e    2
Name: A, dtype: int64

In [12]:
# series의 인덱스를 df 칼럼에 맞추고 아래 로우로 전파 
frame - series

b  d  e
A  0  0  0
B  3  3  3
C  6  6  6
D  9  9  9

In [13]:
series2 = pd.Series(range(3), index = ['b', 'e','f'])
series2 

b    0
e    1
f    2
dtype: int64

In [14]:
frame +series2
# 겹치는 열만 연산 

b   d     e   f
A  0.0 NaN   3.0 NaN
B  3.0 NaN   6.0 NaN
C  6.0 NaN   9.0 NaN
D  9.0 NaN  12.0 NaN

In [15]:
series3 = frame['d']
frame

b   d   e
A  0   1   2
B  3   4   5
C  6   7   8
D  9  10  11

In [16]:
series3

A     1
B     4
C     7
D    10
Name: d, dtype: int64

In [17]:
# 산술 연산자 : 각 로우에 대해 연산 
frame.sub(series3 , axis ='index' ) 
# frame - series3  A행 - 1 , B행 -4 , C행 -7 

b  d  e
A -1  0  1
B -1  0  1
C -1  0  1
D -1  0  1

* 함수 적용과 매핑 

In [18]:
frame =pd.DataFrame(np.random.randn(4,3), 
                    columns = list('bde'),
                    index = ['A', 'B', 'C', 'D'])
frame

b         d         e
A -0.775526 -0.481349 -1.035386
B -1.252228 -0.089307  0.120327
C  0.782473  0.586660 -0.659736
D  1.448221  1.595342  1.205117

In [19]:
# 절대값
np.abs(frame) 

b         d         e
A  0.775526  0.481349  1.035386
B  1.252228  0.089307  0.120327
C  0.782473  0.586660  0.659736
D  1.448221  1.595342  1.205117

In [20]:
# 함수 적용 
frame.apply(lambda x : x +10)

b          d          e
A   9.224474   9.518651   8.964614
B   8.747772   9.910693  10.120327
C  10.782473  10.586660   9.340264
D  11.448221  11.595342  11.205117

In [21]:
f = lambda x : x.max() - x.min()
frame.apply(f)  # 각 칼럼에 대해 최대 -최소값 

b    2.700449
d    2.076691
e    2.240503
dtype: float64

In [22]:
frame.apply(f, axis= 'columns') # 각 로우에 있어 

A    0.554037
B    1.372555
C    1.442209
D    0.390225
dtype: float64

In [23]:
# 각 원소에 적용되는 함수 : 매핑 applymap
format = lambda x : '%.2f' % x 
frame.applymap(format)

b      d      e
A  -0.78  -0.48  -1.04
B  -1.25  -0.09   0.12
C   0.78   0.59  -0.66
D   1.45   1.60   1.21

인덱스 정렬 : sort_index(axis = 0 (디폴트) / 1(열))  
값에 따라 정렬 : sort_values( , by = 'columns' (기준열) )



순위 : rank()

In [24]:
# 동점인 경우 평균 순위 
obj = pd.Series([7, -5, 7,4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [25]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [26]:
# 동점인 경우 먼저 등장한 순서에 따라 순위 
obj.rank(method = 'first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [27]:
# 4 값 : 공동 4등 
obj.rank(method ='min')


0    6.0
1    1.0
2    6.0
3    4.0
4    3.0
5    2.0
6    4.0
dtype: float64

순위의 동률 처리 메서드 : average (평균값) , min(낮은 순위로) , max(높은 순위로) ,  
first(데이터 위치에 따라) , dense( min 적용, 1씩 증가시킴)

* 기술 통계 계산 및  요약

In [28]:
df= pd.DataFrame(np.arange(8).reshape(4,2))
df

0  1
0  0  1
1  2  3
2  4  5
3  6  7

In [29]:
df.sum()

0    12
1    16
dtype: int64

In [30]:
df.sum(axis =1)

0     1
1     5
2     9
3    13
dtype: int64

In [31]:
df.cumsum() # 누적 합

0   1
0   0   1
1   2   4
2   6   9
3  12  16

* 상관관계와 공분산  
df[ 칼럼리스트 ].corr() : 상관관계   
corrwith() : 다른 series나 df와의 상관관계 

* 값 치환하기 df.replace()

In [32]:
data = pd.Series([1, -999, 2, -999, - 1000 , 3])
data

0       1
1    -999
2       2
3    -999
4   -1000
5       3
dtype: int64

In [33]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [34]:
data.replace([-999, -1000], [999, 1000])

0       1
1     999
2       2
3     999
4    1000
5       3
dtype: int64

In [35]:
data.replace({-999 : 9 , -1000 : 10})

0     1
1     9
2     2
3     9
4    10
5     3
dtype: int64

DF 생성 = pd.Dataframe( {키1 : [값], 키2  : [값 ] }, index = [ , ,  ], columns =  [ , , ])

In [36]:
data = np.arange(12).reshape(4,3)
df = pd.DataFrame(data , index = list('abcd'), columns = ['c1', 'c2', 'c3'])
df

c1  c2  c3
a   0   1   2
b   3   4   5
c   6   7   8
d   9  10  11

행과 열 이름 바꾸기이

In [37]:
df.index = df.index.map(lambda x : x.upper())
df

c1  c2  c3
A   0   1   2
B   3   4   5
C   6   7   8
D   9  10  11

In [38]:
# 리스트로 바꾸기 
df.columns = ['col1', 'col2', 'col3']
df.index = ['j', 'k', 'l', 'm']
df

col1  col2  col3
j     0     1     2
k     3     4     5
l     6     7     8
m     9    10    11

In [39]:
# rename() + 딕셔너리로 바꾸기 
df.rename(columns = {'col1' : 'c1'}, inplace = True)
df

c1  col2  col3
j   0     1     2
k   3     4     5
l   6     7     8
m   9    10    11

* 개별화와 양자화  
구간분할(그룹) : pd.cut(x , bins = , labels , include_lowest = T /F)

In [40]:
ages = list(np.random.randint(10 , 40 , size =10))
ages

[39, 18, 29, 20, 32, 30, 13, 12, 23, 29]

In [41]:
# pandas.cut()
bins = [10 , 20 , 30 , 40]  # 10~ 20 / 20~30 / 30~ 40 3그룹 
cats = pd.cut(ages, bins , include_lowest= True) 

In [42]:
cats # 카테고리를 반환함

[(30.0, 40.0], (9.999, 20.0], (20.0, 30.0], (9.999, 20.0], (30.0, 40.0], (20.0, 30.0], (9.999, 20.0], (9.999, 20.0], (20.0, 30.0], (20.0, 30.0]]
Categories (3, interval[float64, right]): [(9.999, 20.0] < (20.0, 30.0] < (30.0, 40.0]]

In [43]:
cats.codes  # 각 데이터들이 어디에 속하는가

array([2, 0, 1, 0, 2, 1, 0, 0, 1, 1], dtype=int8)

In [44]:
cats.categories

IntervalIndex([(9.999, 20.0], (20.0, 30.0], (30.0, 40.0]], dtype='interval[float64, right]')

In [45]:
pd.value_counts(cats) # 구간당 데이터 수 

(9.999, 20.0]    4
(20.0, 30.0]     4
(30.0, 40.0]     2
dtype: int64

 cut 함수에 경계값 bins 를 넘기지 않고 그룹의 개수를 넘기면 자동으로 균등한 길이의 그룹 분할 

In [46]:
data = np.random.rand(20)
print(data , '\n')
pd.cut(data ,4 , precision =2 ) # precision : 소수점 2자리 제한 

[0.54423601 0.47207231 0.8832982  0.77588848 0.37637305 0.28835747
 0.86388467 0.78999783 0.7607567  0.95111231 0.69476583 0.43604579
 0.80597767 0.08705629 0.95191114 0.68907262 0.9252423  0.47135936
 0.44614638 0.30308951] 



[(0.52, 0.74], (0.3, 0.52], (0.74, 0.95], (0.74, 0.95], (0.3, 0.52], ..., (0.52, 0.74], (0.74, 0.95], (0.3, 0.52], (0.3, 0.52], (0.086, 0.3]]
Length: 20
Categories (4, interval[float64, right]): [(0.086, 0.3] < (0.3, 0.52] < (0.52, 0.74] < (0.74, 0.95]]

qcut() : 변위수 기준으로 데이터를 자동으로 나눔 

In [47]:
data = np.random.randn(1000)  # 정규분포 따르는 배열 
cats = pd.qcut(data, 4) # 4분위 수로 나눔
cats

[(-3.0189999999999997, -0.672], (-0.672, -0.00371], (0.665, 3.089], (-0.00371, 0.665], (-0.672, -0.00371], ..., (-3.0189999999999997, -0.672], (0.665, 3.089], (0.665, 3.089], (0.665, 3.089], (0.665, 3.089]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.0189999999999997, -0.672] < (-0.672, -0.00371] < (-0.00371, 0.665] <
                                           (0.665, 3.089]]

In [48]:
pd.value_counts(cats)

(-3.0189999999999997, -0.672]    250
(-0.672, -0.00371]               250
(-0.00371, 0.665]                250
(0.665, 3.089]                   250
dtype: int64

In [49]:
cats2 = pd.qcut(data, [0 , 0.1 , 0.5, 0.9 , 1]) # 직접 변위치를 지정 

In [50]:
cats2

[(-3.0189999999999997, -1.266], (-1.266, -0.00371], (1.266, 3.089], (-0.00371, 1.266], (-1.266, -0.00371], ..., (-1.266, -0.00371], (-0.00371, 1.266], (-0.00371, 1.266], (-0.00371, 1.266], (1.266, 3.089]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.0189999999999997, -1.266] < (-1.266, -0.00371] < (-0.00371, 1.266] <
                                           (1.266, 3.089]]

In [51]:
cats2.categories

IntervalIndex([(-3.0189999999999997, -1.266], (-1.266, -0.00371], (-0.00371, 1.266], (1.266, 3.089]], dtype='interval[float64, right]')

* 특이값을 찾고 제외하기

In [52]:
data = pd.DataFrame(np.random.randn(1000,4))  # 1000행 4열 ?
data.shape

(1000, 4)

In [53]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.014686    -0.009660     0.084719     0.039978
std       0.996133     0.993161     1.030489     1.049844
min      -2.745670    -3.249862    -3.441238    -3.233583
25%      -0.714549    -0.694015    -0.608260    -0.654670
50%      -0.039146    -0.016120     0.097252     0.005211
75%       0.662062     0.677649     0.815826     0.753488
max       2.889950     3.240208     2.966662     3.728450

In [54]:
# 컬럼 2에서 절대값이 3 넘어가는 값 
col= data[2]
col[np.abs(col) > 3] # 3개 행 

74    -3.140792
340   -3.006277
434   -3.441238
457   -3.027951
711   -3.156775
Name: 2, dtype: float64

In [55]:
# 모든데이터 (불린 인덱싱)
data[(np.abs(data) > 3).any(1)] # 하나라도 절대값이 3이 넘어가는 행을 반환 

0         1         2         3
74  -1.296785 -1.560177 -3.140792 -0.941344
82  -0.392753 -3.223192 -0.066899  0.307100
137  0.256925 -3.048836  2.966662  2.327785
172  0.401368 -3.249862 -1.605622  0.956419
340 -0.378793 -0.453635 -3.006277  0.431580
413 -1.130344 -1.955881  1.202854  3.293496
428  1.209671 -1.134183  1.546466  3.728450
434 -0.382518 -0.249469 -3.441238  1.234890
457 -0.263261  0.108553 -3.027951  0.210562
571 -1.286014 -0.104538  0.742455 -3.233583
591  1.158379 -1.787633  0.176917  3.274741
612 -1.437812  3.240208 -0.840890  0.335652
642  0.853832 -0.267027  1.110654 -3.024283
711  0.597761 -1.381629 -3.156775  0.363138
721  0.781471  0.403382  0.252710  3.414687
812 -1.232024 -3.083686  0.075366 -1.114885
826 -0.835999 -2.575147 -0.555825  3.227432
897  2.490950  0.428466 -0.850007  3.458172
923  0.457998  0.363357  1.709800  3.022136

In [56]:
# 모든데이터 (불린 인덱싱)
# 데이터의 값이 3이 넘어가는 모든 행
data.loc[ abs(data.values) > 3, : ]

0         1         2         3
74  -1.296785 -1.560177 -3.140792 -0.941344
82  -0.392753 -3.223192 -0.066899  0.307100
137  0.256925 -3.048836  2.966662  2.327785
172  0.401368 -3.249862 -1.605622  0.956419
340 -0.378793 -0.453635 -3.006277  0.431580
413 -1.130344 -1.955881  1.202854  3.293496
428  1.209671 -1.134183  1.546466  3.728450
434 -0.382518 -0.249469 -3.441238  1.234890
457 -0.263261  0.108553 -3.027951  0.210562
571 -1.286014 -0.104538  0.742455 -3.233583
591  1.158379 -1.787633  0.176917  3.274741
612 -1.437812  3.240208 -0.840890  0.335652
642  0.853832 -0.267027  1.110654 -3.024283
711  0.597761 -1.381629 -3.156775  0.363138
721  0.781471  0.403382  0.252710  3.414687
812 -1.232024 -3.083686  0.075366 -1.114885
826 -0.835999 -2.575147 -0.555825  3.227432
897  2.490950  0.428466 -0.850007  3.458172
923  0.457998  0.363357  1.709800  3.022136

In [57]:
# -3이나 3을 초과하는 값을 -3이나 3으로 지정함. 
data[np.abs(data) >3] = np.sign(data) *3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.014686    -0.009295     0.085492     0.037817
std       0.996133     0.990513     1.028053     1.041671
min      -2.745670    -3.000000    -3.000000    -3.000000
25%      -0.714549    -0.694015    -0.608260    -0.654670
50%      -0.039146    -0.016120     0.097252     0.005211
75%       0.662062     0.677649     0.815826     0.753488
max       2.889950     3.000000     2.966662     3.000000

In [58]:
# np.sign(data) : data 값이 양수인지 음수인지에 따라 1 or -1이 담긴 배열 반환
np.sign(data).head()


0    1    2    3
0  1.0  1.0  1.0 -1.0
1  1.0  1.0  1.0 -1.0
2  1.0 -1.0 -1.0  1.0
3 -1.0 -1.0  1.0  1.0
4 -1.0 -1.0  1.0  1.0

* Df, series의 인덱스 순서 재배치(이름바꾸는거 x)

In [59]:
df.sort_index(ascending = False) # 정렬 

c1  col2  col3
m   9    10    11
l   6     7     8
k   3     4     5
j   0     1     2

In [60]:
# take 함수 
df = pd.DataFrame(np.arange(5*4).reshape((5,4)))
# permutatuon : 순서 섞기 
sampler = np.random.permutation(5)  
sampler

array([4, 0, 1, 2, 3])

In [61]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [62]:
df.take(sampler)

0   1   2   3
4  16  17  18  19
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

* 더미 변수 생성 : pd.get_dummies()

In [63]:
df= pd.DataFrame({'key' : ['b','b', 'a', 'c', 'a', 'b'],
                  'data1' : range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [64]:
# key열 범주형 데이터를 더미변수로 변환함 
# a / b /c 
pd.get_dummies(df['key'])
# bbacab

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [65]:
# 칼럼에 접두어 추가한후 df 병합 : get_dummies( , prefix = '칼럼')
dummies = pd.get_dummies(df['key'], prefix ='key')
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [66]:
# df의 data1 열과 더미df 결합 
df_with_dummy = df[['data1']].join(dummies) 
# join함수는 두 df의 행인덱스 기준 결합
df_with_dummy


data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

ex) 영화 평점 데이터 : 한 레코드가 여러 카테고리에 속할경우 (액션/코미디/로맨스)

* 코랩에서 깃허브 파일 다운로드 

In [90]:
# 내 드라이브와 연동
from google.colab import drive 
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [93]:
! las

'주택가격 데이터셋 '		       numpy.ipynb
 Chap01.ipynb			      'pandas 개념.ipynb'
'Colab Notebooks'		       Pokemon_EDA.ipynb
'통계 설문지.docx'		       puffinbrowser
'고객 구매 데이터 전처리 연습.ipynb'   rexpert30viewer-1.exe
'Numpy 기초 연습 '		       SanFranciscoCrime_classification_EDA


In [125]:
cd "/content/drive/My Drive/"

/content/drive/My Drive


In [104]:
!git clone https://github.com/wesm/pydata-book.git

Cloning into 'pydata-book'...
remote: Enumerating objects: 475, done.
remote: Counting objects: 100% (34/34), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 475 (delta 13), reused 25 (delta 11), pack-reused 441
Receiving objects: 100% (475/475), 40.86 MiB | 7.81 MiB/s, done.
Resolving deltas: 100% (150/150), done.
Checking out files: 100% (210/210), done.


In [128]:
path = "pydata-book/datasets/movielens/movies.dat"
movies = pd.read_table( path ,sep = '::', header = None, names = mnames)
movies[:10]

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)


movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

: 영화마다 장르가 여러개 있는 것도 있다.

In [130]:
# 유일한 장르 목록 추출 
all_genres = []
for x in movies.genres :
  all_genres.extend(x.split('|'))   # |구분자로 나누어 all genres 안에 추가 
genres = pd.unique(all_genres)

In [131]:
genres # 장르 목록

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [142]:
# 더미 df 로 생성 
# 행 개수 영화수 / 열 개수 장르수 행렬 생성, 값 0 
zero_matrix = np.zeros((len(movies), len(genres))) 
# df 화
dummies = pd.DataFrame(zero_matrix , columns = genres )

In [143]:
# 각 영화 데이터를 순회하며 dummies의 각 로우 항목을 1로 설정 . 
gen = movies.genres[0] # 첫번째 데이터 장르 
gen.split('|')

['Animation', "Children's", 'Comedy']

dummies의 칼럼은 영화 장르들 / get_indexer(['애니, 아동 , 코미디'] ) : columns에 있는 위치의 배열 반환 

In [145]:
dummies.columns.get_indexer(gen.split('|'))


array([0, 1, 2])

첫번째 영화의 장르들은 각각 칼럼 처음 0 1 2 에 위치함 -> 이 값을 1로 채우면 더미변수가 됨. 

In [149]:
for i, gen  in enumerate(movies.genres) : # 인덱스와 값 
    indices = dummies.columns.get_indexer(gen.split('|')) # 칼럼들 내에서 위치 
    dummies.iloc[i, indices] = 1    # 1로 채움
dummies.head()

Animation  Children's  Comedy  ...  Mystery  Film-Noir  Western
0        1.0         1.0     1.0  ...      0.0        0.0      0.0
1        0.0         1.0     0.0  ...      0.0        0.0      0.0
2        0.0         0.0     1.0  ...      0.0        0.0      0.0
3        0.0         0.0     1.0  ...      0.0        0.0      0.0
4        0.0         0.0     1.0  ...      0.0        0.0      0.0

[5 rows x 18 columns]

In [151]:
# movies와 조합 영화 이름 & 장르 더미 
movies_windic = movies.join(dummies.add_prefix('Genres')) # 더미 df 칼럼에 접두어 Genres를 붙여 결합 
movies_windic.iloc[0] # 첫행 

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
GenresAnimation                              1.0
GenresChildren's                             1.0
GenresComedy                                 1.0
GenresAdventure                              0.0
GenresFantasy                                0.0
GenresRomance                                0.0
GenresDrama                                  0.0
GenresAction                                 0.0
GenresCrime                                  0.0
GenresThriller                               0.0
GenresHorror                                 0.0
GenresSci-Fi                                 0.0
GenresDocumentary                            0.0
GenresWar                                    0.0
GenresMusical                                0.0
GenresMystery                                0.0
GenresFilm-Noir                              0.0
GenresWestern       

In [159]:
# get_dummies 와 cut 조합 
np.random.seed(1234)
values = np.random.rand(10) # rand : 0 ~ 1
values

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581,
       0.27259261, 0.27646426, 0.80187218, 0.95813935, 0.87593263])

In [160]:
bins = [0 , 0.2 , 0.4 , 0.6 ,0.8 , 1 ] # 5구간 
pd.cut(values, bins)

[(0.0, 0.2], (0.6, 0.8], (0.4, 0.6], (0.6, 0.8], (0.6, 0.8], (0.2, 0.4], (0.2, 0.4], (0.8, 1.0], (0.8, 1.0], (0.8, 1.0]]
Categories (5, interval[float64, right]): [(0.0, 0.2] < (0.2, 0.4] < (0.4, 0.6] < (0.6, 0.8] <
                                           (0.8, 1.0]]

In [161]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           1           0           0           0           0
1           0           0           0           1           0
2           0           0           1           0           0
3           0           0           0           1           0
4           0           0           0           1           0
5           0           1           0           0           0
6           0           1           0           0           0
7           0           0           0           0           1
8           0           0           0           0           1
9           0           0           0           0           1