<a href="https://colab.research.google.com/github/jaewon-huh/DA_DS_dreamtree/blob/main/pandas_%EB%B3%B4%EC%B6%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 판다스 복습

In [1]:
import numpy as np
import pandas as pd 

df1 = pd.DataFrame(np.arange(12).reshape(3,4), columns =list('abcd'))
df2 = pd.DataFrame(np.arange(20).reshape(4,5), columns =list('abcde'))

In [ ]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [ ]:
df2

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [ ]:
# 겹치지 않는 부분 : nan
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [ ]:
# 존재하지 않는 부분의 값은 0으로 지정 
df1.add(df2, fill_value= 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

e열과 3행은 Nan 이 아닌 df2의 값으로 출력된다. 
(fill_value = 0 으로 df1의 존재하지 않는 값을 0으로 채움)

* DF와 Series의 연산 

In [ ]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr[0]

array([0, 1, 2, 3])

In [ ]:
# df - series 
arr- arr[0]
# 각 로우에 대해 실행 (브로드 캐스팅)

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [ ]:
frame = pd.DataFrame(np.arange(12).reshape((4,3)), 
                     columns = list('bde'),
                     index = ['A', 'B', 'C', 'D'])
series = frame.iloc[0]  # 0행

In [ ]:
frame

b   d   e
A  0   1   2
B  3   4   5
C  6   7   8
D  9  10  11

In [ ]:
series

b    0
d    1
e    2
Name: A, dtype: int64

In [ ]:
# series의 인덱스를 df 칼럼에 맞추고 아래 로우로 전파 
frame - series

b  d  e
A  0  0  0
B  3  3  3
C  6  6  6
D  9  9  9

In [ ]:
series2 = pd.Series(range(3), index = ['b', 'e','f'])
series2 

b    0
e    1
f    2
dtype: int64

In [ ]:
frame +series2
# 겹치는 열만 연산 

b   d     e   f
A  0.0 NaN   3.0 NaN
B  3.0 NaN   6.0 NaN
C  6.0 NaN   9.0 NaN
D  9.0 NaN  12.0 NaN

In [ ]:
series3 = frame['d']
frame

b   d   e
A  0   1   2
B  3   4   5
C  6   7   8
D  9  10  11

In [ ]:
series3

A     1
B     4
C     7
D    10
Name: d, dtype: int64

In [ ]:
# 산술 연산자 : 각 로우에 대해 연산 
frame.sub(series3 , axis ='index' ) 
# frame - series3  A행 - 1 , B행 -4 , C행 -7 

b  d  e
A -1  0  1
B -1  0  1
C -1  0  1
D -1  0  1

* 함수 적용과 매핑 

In [ ]:
frame =pd.DataFrame(np.random.randn(4,3), 
                    columns = list('bde'),
                    index = ['A', 'B', 'C', 'D'])
frame

b         d         e
A -0.775526 -0.481349 -1.035386
B -1.252228 -0.089307  0.120327
C  0.782473  0.586660 -0.659736
D  1.448221  1.595342  1.205117

In [ ]:
# 절대값
np.abs(frame) 

b         d         e
A  0.775526  0.481349  1.035386
B  1.252228  0.089307  0.120327
C  0.782473  0.586660  0.659736
D  1.448221  1.595342  1.205117

In [ ]:
# 함수 적용 
frame.apply(lambda x : x +10)

b          d          e
A   9.224474   9.518651   8.964614
B   8.747772   9.910693  10.120327
C  10.782473  10.586660   9.340264
D  11.448221  11.595342  11.205117

In [ ]:
f = lambda x : x.max() - x.min()
frame.apply(f)  # 각 칼럼에 대해 최대 -최소값 

b    2.700449
d    2.076691
e    2.240503
dtype: float64

In [ ]:
frame.apply(f, axis= 'columns') # 각 로우에 있어 

A    0.554037
B    1.372555
C    1.442209
D    0.390225
dtype: float64

In [ ]:
# 각 원소에 적용되는 함수 : 매핑 applymap
format = lambda x : '%.2f' % x 
frame.applymap(format)

b      d      e
A  -0.78  -0.48  -1.04
B  -1.25  -0.09   0.12
C   0.78   0.59  -0.66
D   1.45   1.60   1.21

인덱스 정렬 : sort_index(axis = 0 (디폴트) / 1(열))  
값에 따라 정렬 : sort_values( , by = 'columns' (기준열) )



순위 : rank()

In [ ]:
# 동점인 경우 평균 순위 
obj = pd.Series([7, -5, 7,4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [ ]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [ ]:
# 동점인 경우 먼저 등장한 순서에 따라 순위 
obj.rank(method = 'first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [ ]:
# 4 값 : 공동 4등 
obj.rank(method ='min')


0    6.0
1    1.0
2    6.0
3    4.0
4    3.0
5    2.0
6    4.0
dtype: float64

순위의 동률 처리 메서드 : average (평균값) , min(낮은 순위로) , max(높은 순위로) ,  
first(데이터 위치에 따라) , dense( min 적용, 1씩 증가시킴)

* 기술 통계 계산 및  요약

In [ ]:
df= pd.DataFrame(np.arange(8).reshape(4,2))
df

0  1
0  0  1
1  2  3
2  4  5
3  6  7

In [ ]:
df.sum()

0    12
1    16
dtype: int64

In [ ]:
df.sum(axis =1)

0     1
1     5
2     9
3    13
dtype: int64

In [ ]:
df.cumsum() # 누적 합

0   1
0   0   1
1   2   4
2   6   9
3  12  16

* 상관관계와 공분산  
df[ 칼럼리스트 ].corr() : 상관관계   
corrwith() : 다른 series나 df와의 상관관계 

### 7. 데이터 정제 및 준비 

* 값 치환하기 df.replace()

In [ ]:
data = pd.Series([1, -999, 2, -999, - 1000 , 3])
data

0       1
1    -999
2       2
3    -999
4   -1000
5       3
dtype: int64

In [ ]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [ ]:
data.replace([-999, -1000], [999, 1000])

0       1
1     999
2       2
3     999
4    1000
5       3
dtype: int64

In [ ]:
data.replace({-999 : 9 , -1000 : 10})

0     1
1     9
2     2
3     9
4    10
5     3
dtype: int64

DF 생성 = pd.Dataframe( {키1 : [값], 키2  : [값 ] }, index = [ , ,  ], columns =  [ , , ])

In [ ]:
data = np.arange(12).reshape(4,3)
df = pd.DataFrame(data , index = list('abcd'), columns = ['c1', 'c2', 'c3'])
df

c1  c2  c3
a   0   1   2
b   3   4   5
c   6   7   8
d   9  10  11

행과 열 이름 바꾸기이

In [ ]:
df.index = df.index.map(lambda x : x.upper())
df

c1  c2  c3
A   0   1   2
B   3   4   5
C   6   7   8
D   9  10  11

In [ ]:
# 리스트로 바꾸기 
df.columns = ['col1', 'col2', 'col3']
df.index = ['j', 'k', 'l', 'm']
df

col1  col2  col3
j     0     1     2
k     3     4     5
l     6     7     8
m     9    10    11

In [ ]:
# rename() + 딕셔너리로 바꾸기 
df.rename(columns = {'col1' : 'c1'}, inplace = True)
df

c1  col2  col3
j   0     1     2
k   3     4     5
l   6     7     8
m   9    10    11

* 개별화와 양자화  
구간분할(그룹) : pd.cut(x , bins = , labels , include_lowest = T /F)

In [ ]:
ages = list(np.random.randint(10 , 40 , size =10))
ages

[39, 18, 29, 20, 32, 30, 13, 12, 23, 29]

In [ ]:
# pandas.cut()
bins = [10 , 20 , 30 , 40]  # 10~ 20 / 20~30 / 30~ 40 3그룹 
cats = pd.cut(ages, bins , include_lowest= True) 

In [ ]:
cats # 카테고리를 반환함

[(30.0, 40.0], (9.999, 20.0], (20.0, 30.0], (9.999, 20.0], (30.0, 40.0], (20.0, 30.0], (9.999, 20.0], (9.999, 20.0], (20.0, 30.0], (20.0, 30.0]]
Categories (3, interval[float64, right]): [(9.999, 20.0] < (20.0, 30.0] < (30.0, 40.0]]

In [ ]:
cats.codes  # 각 데이터들이 어디에 속하는가

array([2, 0, 1, 0, 2, 1, 0, 0, 1, 1], dtype=int8)

In [ ]:
cats.categories

IntervalIndex([(9.999, 20.0], (20.0, 30.0], (30.0, 40.0]], dtype='interval[float64, right]')

In [ ]:
pd.value_counts(cats) # 구간당 데이터 수 

(9.999, 20.0]    4
(20.0, 30.0]     4
(30.0, 40.0]     2
dtype: int64

 cut 함수에 경계값 bins 를 넘기지 않고 그룹의 개수를 넘기면 자동으로 균등한 길이의 그룹 분할 

In [ ]:
data = np.random.rand(20)
print(data , '\n')
pd.cut(data ,4 , precision =2 ) # precision : 소수점 2자리 제한 

[0.54423601 0.47207231 0.8832982  0.77588848 0.37637305 0.28835747
 0.86388467 0.78999783 0.7607567  0.95111231 0.69476583 0.43604579
 0.80597767 0.08705629 0.95191114 0.68907262 0.9252423  0.47135936
 0.44614638 0.30308951] 



[(0.52, 0.74], (0.3, 0.52], (0.74, 0.95], (0.74, 0.95], (0.3, 0.52], ..., (0.52, 0.74], (0.74, 0.95], (0.3, 0.52], (0.3, 0.52], (0.086, 0.3]]
Length: 20
Categories (4, interval[float64, right]): [(0.086, 0.3] < (0.3, 0.52] < (0.52, 0.74] < (0.74, 0.95]]

qcut() : 변위수 기준으로 데이터를 자동으로 나눔 

In [ ]:
data = np.random.randn(1000)  # 정규분포 따르는 배열 
cats = pd.qcut(data, 4) # 4분위 수로 나눔
cats

[(-3.0189999999999997, -0.672], (-0.672, -0.00371], (0.665, 3.089], (-0.00371, 0.665], (-0.672, -0.00371], ..., (-3.0189999999999997, -0.672], (0.665, 3.089], (0.665, 3.089], (0.665, 3.089], (0.665, 3.089]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.0189999999999997, -0.672] < (-0.672, -0.00371] < (-0.00371, 0.665] <
                                           (0.665, 3.089]]

In [ ]:
pd.value_counts(cats)

(-3.0189999999999997, -0.672]    250
(-0.672, -0.00371]               250
(-0.00371, 0.665]                250
(0.665, 3.089]                   250
dtype: int64

In [ ]:
cats2 = pd.qcut(data, [0 , 0.1 , 0.5, 0.9 , 1]) # 직접 변위치를 지정 

In [ ]:
cats2

[(-3.0189999999999997, -1.266], (-1.266, -0.00371], (1.266, 3.089], (-0.00371, 1.266], (-1.266, -0.00371], ..., (-1.266, -0.00371], (-0.00371, 1.266], (-0.00371, 1.266], (-0.00371, 1.266], (1.266, 3.089]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.0189999999999997, -1.266] < (-1.266, -0.00371] < (-0.00371, 1.266] <
                                           (1.266, 3.089]]

In [ ]:
cats2.categories

IntervalIndex([(-3.0189999999999997, -1.266], (-1.266, -0.00371], (-0.00371, 1.266], (1.266, 3.089]], dtype='interval[float64, right]')

* 특이값을 찾고 제외하기

In [ ]:
data = pd.DataFrame(np.random.randn(1000,4))  # 1000행 4열 ?
data.shape

(1000, 4)

In [ ]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.014686    -0.009660     0.084719     0.039978
std       0.996133     0.993161     1.030489     1.049844
min      -2.745670    -3.249862    -3.441238    -3.233583
25%      -0.714549    -0.694015    -0.608260    -0.654670
50%      -0.039146    -0.016120     0.097252     0.005211
75%       0.662062     0.677649     0.815826     0.753488
max       2.889950     3.240208     2.966662     3.728450

In [ ]:
# 컬럼 2에서 절대값이 3 넘어가는 값 
col= data[2]
col[np.abs(col) > 3] # 3개 행 

74    -3.140792
340   -3.006277
434   -3.441238
457   -3.027951
711   -3.156775
Name: 2, dtype: float64

In [ ]:
# 모든데이터 (불린 인덱싱)
data[(np.abs(data) > 3).any(1)] # 하나라도 절대값이 3이 넘어가는 행을 반환 

0         1         2         3
74  -1.296785 -1.560177 -3.140792 -0.941344
82  -0.392753 -3.223192 -0.066899  0.307100
137  0.256925 -3.048836  2.966662  2.327785
172  0.401368 -3.249862 -1.605622  0.956419
340 -0.378793 -0.453635 -3.006277  0.431580
413 -1.130344 -1.955881  1.202854  3.293496
428  1.209671 -1.134183  1.546466  3.728450
434 -0.382518 -0.249469 -3.441238  1.234890
457 -0.263261  0.108553 -3.027951  0.210562
571 -1.286014 -0.104538  0.742455 -3.233583
591  1.158379 -1.787633  0.176917  3.274741
612 -1.437812  3.240208 -0.840890  0.335652
642  0.853832 -0.267027  1.110654 -3.024283
711  0.597761 -1.381629 -3.156775  0.363138
721  0.781471  0.403382  0.252710  3.414687
812 -1.232024 -3.083686  0.075366 -1.114885
826 -0.835999 -2.575147 -0.555825  3.227432
897  2.490950  0.428466 -0.850007  3.458172
923  0.457998  0.363357  1.709800  3.022136

In [ ]:
# 모든데이터 (불린 인덱싱)
# 데이터의 값이 3이 넘어가는 모든 행
data.loc[ abs(data.values) > 3, : ]

0         1         2         3
74  -1.296785 -1.560177 -3.140792 -0.941344
82  -0.392753 -3.223192 -0.066899  0.307100
137  0.256925 -3.048836  2.966662  2.327785
172  0.401368 -3.249862 -1.605622  0.956419
340 -0.378793 -0.453635 -3.006277  0.431580
413 -1.130344 -1.955881  1.202854  3.293496
428  1.209671 -1.134183  1.546466  3.728450
434 -0.382518 -0.249469 -3.441238  1.234890
457 -0.263261  0.108553 -3.027951  0.210562
571 -1.286014 -0.104538  0.742455 -3.233583
591  1.158379 -1.787633  0.176917  3.274741
612 -1.437812  3.240208 -0.840890  0.335652
642  0.853832 -0.267027  1.110654 -3.024283
711  0.597761 -1.381629 -3.156775  0.363138
721  0.781471  0.403382  0.252710  3.414687
812 -1.232024 -3.083686  0.075366 -1.114885
826 -0.835999 -2.575147 -0.555825  3.227432
897  2.490950  0.428466 -0.850007  3.458172
923  0.457998  0.363357  1.709800  3.022136

In [ ]:
# -3이나 3을 초과하는 값을 -3이나 3으로 지정함. 
data[np.abs(data) >3] = np.sign(data) *3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.014686    -0.009295     0.085492     0.037817
std       0.996133     0.990513     1.028053     1.041671
min      -2.745670    -3.000000    -3.000000    -3.000000
25%      -0.714549    -0.694015    -0.608260    -0.654670
50%      -0.039146    -0.016120     0.097252     0.005211
75%       0.662062     0.677649     0.815826     0.753488
max       2.889950     3.000000     2.966662     3.000000

In [ ]:
# np.sign(data) : data 값이 양수인지 음수인지에 따라 1 or -1이 담긴 배열 반환
np.sign(data).head()


0    1    2    3
0  1.0  1.0  1.0 -1.0
1  1.0  1.0  1.0 -1.0
2  1.0 -1.0 -1.0  1.0
3 -1.0 -1.0  1.0  1.0
4 -1.0 -1.0  1.0  1.0

* Df, series의 인덱스 순서 재배치(이름바꾸는거 x)

In [ ]:
df.sort_index(ascending = False) # 정렬 

c1  col2  col3
m   9    10    11
l   6     7     8
k   3     4     5
j   0     1     2

In [ ]:
# take 함수 
df = pd.DataFrame(np.arange(5*4).reshape((5,4)))
# permutatuon : 순서 섞기 
sampler = np.random.permutation(5)  
sampler

array([4, 0, 1, 2, 3])

In [ ]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [ ]:
df.take(sampler)

0   1   2   3
4  16  17  18  19
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

* 더미 변수 생성 : pd.get_dummies()

In [ ]:
df= pd.DataFrame({'key' : ['b','b', 'a', 'c', 'a', 'b'],
                  'data1' : range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [ ]:
# key열 범주형 데이터를 더미변수로 변환함 
# a / b /c 
pd.get_dummies(df['key'])
# bbacab

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [ ]:
# 칼럼에 접두어 추가한후 df 병합 : get_dummies( , prefix = '칼럼')
dummies = pd.get_dummies(df['key'], prefix ='key')
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [ ]:
# df의 data1 열과 더미df 결합 
df_with_dummy = df[['data1']].join(dummies) 
# join함수는 두 df의 행인덱스 기준 결합
df_with_dummy


data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

ex) 영화 평점 데이터 : 한 레코드가 여러 카테고리에 속할경우 (액션/코미디/로맨스)

* 코랩에서 깃허브 파일 다운로드 

In [ ]:
# 내 드라이브와 연동
from google.colab import drive 
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
! las

'주택가격 데이터셋 '		       numpy.ipynb
 Chap01.ipynb			      'pandas 개념.ipynb'
'Colab Notebooks'		       Pokemon_EDA.ipynb
'통계 설문지.docx'		       puffinbrowser
'고객 구매 데이터 전처리 연습.ipynb'   rexpert30viewer-1.exe
'Numpy 기초 연습 '		       SanFranciscoCrime_classification_EDA


In [ ]:
cd "/content/drive/My Drive/"

/content/drive/My Drive


In [ ]:
!git clone https://github.com/wesm/pydata-book.git

Cloning into 'movies.dat'...
fatal: repository 'https://github.com/wesm/pydata-book/blob/2nd-edition/datasets/movielens/movies.dat/' not found


In [ ]:
path = "pydata-book/datasets/movielens/movies.dat"
movies = pd.read_table( path ,sep = '::', header = None, names = mnames)
movies[:10]

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)


movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

: 영화마다 장르가 여러개 있는 것도 있다.

In [ ]:
# 유일한 장르 목록 추출 
all_genres = []
for x in movies.genres :
  all_genres.extend(x.split('|'))   # |구분자로 나누어 all genres 안에 추가 
genres = pd.unique(all_genres)

In [ ]:
genres # 장르 목록

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [ ]:
# 더미 df 로 생성 
# 행 개수 영화수 / 열 개수 장르수 행렬 생성, 값 0 
zero_matrix = np.zeros((len(movies), len(genres))) 
# df 화
dummies = pd.DataFrame(zero_matrix , columns = genres )

In [ ]:
# 각 영화 데이터를 순회하며 dummies의 각 로우 항목을 1로 설정 . 
gen = movies.genres[0] # 첫번째 데이터 장르 
gen.split('|')

['Animation', "Children's", 'Comedy']

dummies의 칼럼은 영화 장르들 / get_indexer(['애니, 아동 , 코미디'] ) : columns에 있는 위치의 배열 반환 

In [ ]:
dummies.columns.get_indexer(gen.split('|'))


array([0, 1, 2])

첫번째 영화의 장르들은 각각 칼럼 처음 0 1 2 에 위치함 -> 이 값을 1로 채우면 더미변수가 됨. 

In [ ]:
for i, gen  in enumerate(movies.genres) : # 인덱스와 값 
    indices = dummies.columns.get_indexer(gen.split('|')) # 칼럼들 내에서 위치 
    dummies.iloc[i, indices] = 1    # 1로 채움
dummies.head()

Animation  Children's  Comedy  ...  Mystery  Film-Noir  Western
0        1.0         1.0     1.0  ...      0.0        0.0      0.0
1        0.0         1.0     0.0  ...      0.0        0.0      0.0
2        0.0         0.0     1.0  ...      0.0        0.0      0.0
3        0.0         0.0     1.0  ...      0.0        0.0      0.0
4        0.0         0.0     1.0  ...      0.0        0.0      0.0

[5 rows x 18 columns]

In [ ]:
# movies와 조합 영화 이름 & 장르 더미 
movies_windic = movies.join(dummies.add_prefix('Genres')) # 더미 df 칼럼에 접두어 Genres를 붙여 결합 
movies_windic.iloc[0] # 첫행 

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
GenresAnimation                              1.0
GenresChildren's                             1.0
GenresComedy                                 1.0
GenresAdventure                              0.0
GenresFantasy                                0.0
GenresRomance                                0.0
GenresDrama                                  0.0
GenresAction                                 0.0
GenresCrime                                  0.0
GenresThriller                               0.0
GenresHorror                                 0.0
GenresSci-Fi                                 0.0
GenresDocumentary                            0.0
GenresWar                                    0.0
GenresMusical                                0.0
GenresMystery                                0.0
GenresFilm-Noir                              0.0
GenresWestern       

In [ ]:
# get_dummies 와 cut 조합 
np.random.seed(1234)
values = np.random.rand(10) # rand : 0 ~ 1
values

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581,
       0.27259261, 0.27646426, 0.80187218, 0.95813935, 0.87593263])

In [ ]:
bins = [0 , 0.2 , 0.4 , 0.6 ,0.8 , 1 ] # 5구간 
pd.cut(values, bins)

[(0.0, 0.2], (0.6, 0.8], (0.4, 0.6], (0.6, 0.8], (0.6, 0.8], (0.2, 0.4], (0.2, 0.4], (0.8, 1.0], (0.8, 1.0], (0.8, 1.0]]
Categories (5, interval[float64, right]): [(0.0, 0.2] < (0.2, 0.4] < (0.4, 0.6] < (0.6, 0.8] <
                                           (0.8, 1.0]]

In [ ]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           1           0           0           0           0
1           0           0           0           1           0
2           0           0           1           0           0
3           0           0           0           1           0
4           0           0           0           1           0
5           0           1           0           0           0
6           0           1           0           0           0
7           0           0           0           0           1
8           0           0           0           0           1
9           0           0           0           0           1

* 문자열 다루기 

In [12]:
# 문자열 split 
val = 'a,b,   git'
val.split(',')

['a', 'b', '   git']

In [13]:
# strip 메서드와 조합 : 공백 제거 
pieces = [x.strip () for x in val.split(',')]
pieces

['a', 'b', 'git']

In [14]:
# 문자열 더하기 연산 join
'::'.join(pieces)

'a::b::git'

In [15]:
# x in str - T/ F  , str.index('x')
'a' in val , val.index('a')

(True, 0)

In [19]:
#str.find('x')  : T = index / F =  -1
val.find('c')


-1

In [20]:
# count() 특정 문자열이 몇번 등장 
val.count(',')

2

In [21]:
# 특정 값 치환 
val.replace(',' , ' :')


'a :b :   git'

파이썬 내장 문자열 함수 : 
startswith , endswith - 접두사 접미사 T/F ,  
join : 이어 붙이기   
split :  구분자로 분리   
find, rfind : 찾는 문자의 인덱스 위치 반환 . 없으면 -1   
lower,upper : 대소문자 변환 
 

* 정규표현식 !! : 특정한 문자열(패턴)을 찾아낼때 사용하는 표현식   
\s+ : 하나 이상의 공백문자를 의미 

In [27]:
import re  # re모듈 : 패턴 매칭 ,치환 , 분리 
text = 'foo bar\t baz\t qux'    # \t : 문자열 사이 탭간격
# split으로 분리
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [29]:
# complie로 정규 표현식 컴파일 
regex =re.compile('\s+')
regex

re.compile(r'\s+', re.UNICODE)

In [33]:
print(regex.split(text))
print('\n')
print(regex.findall(text))

['foo', 'bar', 'baz', 'qux']


[' ', '\t ', '\t ']


* 이메일 주소를 검사하는 정규표현식  
wodnjs8201@naver.com =   
[0-9a-zA-Z]([-_\.]?[0-9a-zA-Z]) *@ [0-9a-zA-Z]([-_\.]?[0-9a-zA-Z]) * \. [a-zA-Z]{2,3}  
앞 아이디 :[a-z 대소문자,0-9](중간에 -_\.같은 문자 있을수도) /    
골뱅이 @ /  
사이트 : [a-z, 0-9]/  
.(dot) /  
com,kr : [a-z]{2,3} 2에서 3자리 문자열 


In [35]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

In [36]:
regex =re.compile(pattern , flags = re.IGNORECASE)  # 컴파일 (flags : 대소문자 무시 )


In [37]:
# 정규식과 매치되는 몯든 문자열을 리스트로 반환 
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [42]:
# search : 문자열 전체를 검색해 정규식과 매치되는지 
m = regex.search(text)
m # 첫번째 이메일 주소와 정규표현 패틴의 문자열 내 위치 
text[m.start():m.end()]

'dave@google.com'

In [43]:
# match : 문자열의 시작점부터 정규식과 매치되는지 
print(regex.match(text))

None


In [44]:
# sub : 찾은 패턴을 주어진 문자열로 치환 
print(regex.sub('REDACTED', text))  # 이메일 패턴 문자열을 'REDACTED'로 치환 

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [45]:
# 이메일 주소를 찾아 구성별로 구분 (사용자 이름 / 도메인이름 / 도메인접미사)
# 각 패턴을 괄호로 묶어줌
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'
regex = re.compile(pattern , flags =re.IGNORECASE)

In [46]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [49]:
m = regex.match('gjwos1231@naver.com')
m.groups() 
# 그룹 메서드로 각 패턴 컴포넌트의 튜플 

('gjwos1231', 'naver', 'com')

정규 표현식 메서드   
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'  
regex = re.compile(pattern)  
regex.findall() : 정규식과 매치되는 모든 문자열을 리스트로 반환   
finditer() : iter 객체로 반환  
match() : 문자열의 시작점부터 정규식(패턴)과 매치되는지 조사   
search() : 문자열에서 패턴과 일치하는 내용을 찾고 match 객체 반환  
match 객체 -> group() , start() , end(), span()

*벡터화된 문자열 메서드   
cat: 구분자와 함께 요소별로 문자열 이어 붙이기   
contains : 포함 ? , get() : i번째 요소 반환 
count : 일치하는 패턴수 반환 등등

### 8. 데이터 준비 : 조인 , 병합 , 변형 

In [52]:
# 멀티인덱스 
data = pd.Series(np.random.randn(9), 
                 index = [ ['a','a','a','b','b','c','c','d','d'],
                          [1,2,3,1,3,1,2,2,3]])
data

a  1   -0.494415
   2    0.220973
   3   -1.785051
b  1   -0.386054
   3   -1.259323
c  1   -0.032322
   2   -0.839133
d  2   -1.501241
   3    0.543627
dtype: float64

In [57]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [59]:
data.loc[['b','c']]

b  1   -0.386054
   3   -1.259323
c  1   -0.032322
   2   -0.839133
dtype: float64

In [61]:
data.loc[:, 2] # 하위 계층의 객체 선택 2

a    0.220973
c   -0.839133
d   -1.501241
dtype: float64

In [63]:
data.loc['a', 2]

0.2209725916050341

In [64]:
# unstack() 
data.unstack()

1         2         3
a -0.494415  0.220973 -1.785051
b -0.386054       NaN -1.259323
c -0.032322 -0.839133       NaN
d       NaN -1.501241  0.543627

In [66]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                     index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                     columns=[['Ohio', 'Ohio', 'Colorado'],
                              ['Green', 'Red', 'Green']])
frame.index.names = ['key1', 'key2']
frame.columns.names = ['state', 'color']
frame


state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [67]:
# 계층 순서 변경 swaplevel 
frame.swaplevel('key1', 'key2')  # 원본은 변경 x 

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [73]:
# 인덱스 정렬
frame.sort_index(level= 1)  # level1 :  key2, ascending

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

* 계층별 요약 통계 

In [74]:
# key2 : 1 , 2 별 로우 합 
frame.sum(level = 'key2')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  


state  Ohio     Colorado
color Green Red    Green
key2                    
1         6   8       10
2        12  14       16

In [79]:
frame.sum(level = 'color', axis =1 ) # 기준 color 합 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  """Entry point for launching an IPython kernel.


color      Green  Red
key1 key2            
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

set_index() :  칼럼을 인덱스로 설정   
reindex(새인덱스 배열) : 인덱스 지정   
reset_index() : 인덱스 원상태 (기존인덱스는 열로)

* 데이터 합치기 : merge , join , concat()

In [81]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                    'data1': range(7)})
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],
                    'data2': range(3)})
df1


key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [82]:

df2

key  data2
0   a      0
1   b      1
2   d      2

In [83]:
# 기준열 key : 
pd.merge(df1,df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [85]:
# 두 df에 중복된 컬럼 x 
df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                    'data1': range(7)})
df4 = pd.DataFrame({'rkey': ['a', 'b', 'd'],
                    'data2': range(3)})
pd.merge(df3, df4, left_on='lkey', right_on='rkey')
# c,d (X) : merge - 교집합 how = 'inner 

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0

In [89]:
# concat() 
s1 = pd.Series([0, 1], index=['a', 'b'])
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = pd.Series([5, 6], index=['f', 'g'])

pd.concat([s1, s2, s3]) # axis =0 

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [91]:
pd.concat([s1,s2,s3] , axis =1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [96]:
pd.concat([s1, s2, s3], axis=1, keys=['one', 'two', 'three'])


one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [93]:
s4 = pd.concat([s1,s3])
s4

a    0
b    1
f    5
g    6
dtype: int64

In [95]:
# 계층적 색인 keys 인자로 개별 Series 구분 
# s1 : one / s1 = two /  s3  : three 
result = pd.concat([s1, s1, s3], keys=['one', 'two', 'three'])
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [98]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=['a', 'b', 'c'],
                   columns=['one', 'two'])
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=['a', 'c'],
                   columns=['three', 'four'])
df1

one  two
a    0    1
b    2    3
c    4    5

In [99]:
df2

three  four
a      5     6
c      7     8

In [100]:
# concat 인자로 dictionary 넘기면 사전의 키가 keys 옵션으로 적용 
pd.concat({'level1': df1, 'level2': df2}, axis=1)


level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [101]:
# 두 df의 인덱스가 겹치는 경우 
a = pd.Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],
              index=['f', 'e', 'd', 'c', 'b', 'a'])
b = pd.Series(np.arange(len(a), dtype=np.float64),
              index=['f', 'e', 'd', 'c', 'b', 'a'])
b[-1] = np.nan
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [102]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [106]:
pd.concat([a,b], axis =1 )

0    1
f  NaN  0.0
e  2.5  1.0
d  NaN  2.0
c  3.5  3.0
b  4.5  4.0
a  NaN  NaN

In [108]:
np.where(pd.isnull(a), b ,a)  # a가 nan이면 b값 , F이면 a 값

array([0. , 2.5, 2. , 3.5, 4.5, nan])

In [110]:
# 동일한 기능 + 시리즈 정렬
b[:-2].combine_first(a[2:])

a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

* 재형성과 피벗   
stack() : df의 칼럼을 로우로 피벗.   
unstack() : 로우를 칼럼으로 피벗

In [111]:
data = pd.DataFrame(np.arange(6).reshape((2, 3)),
                    index=pd.Index(['Ohio', 'Colorado'], name='state'),
                    columns=pd.Index(['one', 'two', 'three'],
                    name='number'))
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [113]:
result = data.stack()
result # 멀티 인덱스 series 객체가 됨 

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [114]:
result.unstack()

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

: 가장 하위 레벨 부터 끄집어 낸다.

In [115]:
# 레벨숫자나 이름을 지정 
result.unstack(0) # state row 를 칼럼으로 

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [116]:
result.unstack('state')

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [117]:
s1 = pd.Series([0, 1, 2, 3], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([4, 5, 6], index=['c', 'd', 'e'])
data2 = pd.concat([s1, s2], keys=['one', 'two'])
data2


one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: int64

In [118]:
# abcdcde -> 칼럼으로 abcde
data2.unstack()

a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0

In [120]:
# stack()은 누락된 데이터를 자동으로 제외 
data2.unstack().stack()  # abcd - cde

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
two  c    4.0
     d    5.0
     e    6.0
dtype: float64

In [121]:
# unstack시 unstack 레벨은 칼럼의 최하 단계로 
df = pd.DataFrame({'left': result, 'right': result + 5},
                  columns=pd.Index(['left', 'right'], name='side'))
df

side             left  right
state    number             
Ohio     one        0      5
         two        1      6
         three      2      7
Colorado one        3      8
         two        4      9
         three      5     10

In [122]:
# column side - state 순
df.unstack('state')

side   left          right         
state  Ohio Colorado  Ohio Colorado
number                             
one       0        3     5        8
two       1        4     6        9
three     2        5     7       10

* 긴형식에서 넓
은 형식으로 피벗.   
: 시계열 데이터 

In [124]:
cd "/content/drive/My Drive/"

/content/drive/My Drive


In [129]:
data = pd.read_csv('pydata-book/examples/macrodata.csv')
data.head()

year  quarter   realgdp  realcons  ...  unemp      pop  infl  realint
0  1959.0      1.0  2710.349    1707.4  ...    5.8  177.146  0.00     0.00
1  1959.0      2.0  2778.801    1733.7  ...    5.1  177.830  2.34     0.74
2  1959.0      3.0  2775.488    1751.8  ...    5.3  178.657  2.74     1.09
3  1959.0      4.0  2785.204    1753.7  ...    5.6  179.386  0.27     4.06
4  1960.0      1.0  2847.699    1770.5  ...    5.2  180.007  2.31     1.19

[5 rows x 14 columns]

In [130]:
periods = pd.PeriodIndex(year=data.year, quarter=data.quarter,
                         name='date')       # PeriodIndex : 연도와 분기 칼럼을 합침 
columns = pd.Index(['realgdp', 'infl', 'unemp'], name='item')
data = data.reindex(columns=columns)
data.index = periods.to_timestamp('D', 'end')
ldata = data.stack().reset_index().rename(columns={0: 'value'})


In [131]:
ldata.head()

date     item     value
0 1959-03-31 23:59:59.999999999  realgdp  2710.349
1 1959-03-31 23:59:59.999999999     infl     0.000
2 1959-03-31 23:59:59.999999999    unemp     5.800
3 1959-06-30 23:59:59.999999999  realgdp  2778.801
4 1959-06-30 23:59:59.999999999     infl     2.340

p1.pivot(index=None, columns=None, values=None

In [135]:
pivoted = ldata.pivot('date', 'item', 'value')
pivoted

item                           infl    realgdp  unemp
date                                                 
1959-03-31 23:59:59.999999999  0.00   2710.349    5.8
1959-06-30 23:59:59.999999999  2.34   2778.801    5.1
1959-09-30 23:59:59.999999999  2.74   2775.488    5.3
1959-12-31 23:59:59.999999999  0.27   2785.204    5.6
1960-03-31 23:59:59.999999999  2.31   2847.699    5.2
...                             ...        ...    ...
2008-09-30 23:59:59.999999999 -3.16  13324.600    6.0
2008-12-31 23:59:59.999999999 -8.79  13141.920    6.9
2009-03-31 23:59:59.999999999  0.94  12925.410    8.1
2009-06-30 23:59:59.999999999  3.37  12901.504    9.2
2009-09-30 23:59:59.999999999  3.56  12990.341    9.6

[203 rows x 3 columns]

In [136]:
ldata['value2'] = np.random.randn(len(ldata))
ldata[:10]

date     item     value    value2
0 1959-03-31 23:59:59.999999999  realgdp  2710.349 -0.995762
1 1959-03-31 23:59:59.999999999     infl     0.000 -0.816872
2 1959-03-31 23:59:59.999999999    unemp     5.800 -0.413208
3 1959-06-30 23:59:59.999999999  realgdp  2778.801 -1.693434
4 1959-06-30 23:59:59.999999999     infl     2.340  0.228750
5 1959-06-30 23:59:59.999999999    unemp     5.100 -0.364706
6 1959-09-30 23:59:59.999999999  realgdp  2775.488 -0.014094
7 1959-09-30 23:59:59.999999999     infl     2.740  0.209084
8 1959-09-30 23:59:59.999999999    unemp     5.300 -0.170748
9 1959-12-31 23:59:59.999999999  realgdp  2785.204  1.912422

In [138]:
pivoted = ldata.pivot('date', 'item') # value 인자 미포함 
pivoted[:5] # 5행만 

value            ...    value2          
item                           infl   realgdp  ...   realgdp     unemp
date                                           ...                    
1959-03-31 23:59:59.999999999  0.00  2710.349  ... -0.995762 -0.413208
1959-06-30 23:59:59.999999999  2.34  2778.801  ... -1.693434 -0.364706
1959-09-30 23:59:59.999999999  2.74  2775.488  ... -0.014094 -0.170748
1959-12-31 23:59:59.999999999  0.27  2785.204  ...  1.912422 -0.358663
1960-03-31 23:59:59.999999999  2.31  2847.699  ... -1.021791  0.850801

[5 rows x 6 columns]

* 넓은 형식에서 긴 형식으로 피벗 : pandas.melt 

In [140]:
df = pd.DataFrame({'key': ['foo', 'bar', 'baz'],
                   'A': [1, 2, 3],
                   'B': [4, 5, 6],
                   'C': [7, 8, 9]})
df

key  A  B  C
0  foo  1  4  7
1  bar  2  5  8
2  baz  3  6  9

In [142]:
# 'key' 칼럼을 구분자로 하여 병합 key - variable (변수들) - value (데이터)
melted = pd.melt(df, ['key'])
melted

# 3x3 df가 9개의 개별 데이터로 

key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6
6  foo        C      7
7  bar        C      8
8  baz        C      9

In [143]:
# 사용할 변수 지정 
pd.melt(df, id_vars = ['key'], value_vars =['A', 'B'])

key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6